### ISSUE TITLE
Apache Http Client - org/apache/http/ssl/TrustStrategy

### ISSUE THREAD

**Issue by bodalot** [lightcouch/LightCouch#40]
This crease an issue when I try to autowire the CouchdbClient class in a spring project.

Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.lightcouch.CouchDbClient com.linfix.services.UserService.couchDbClient; nested exception is java.lang.NoClassDefFoundError: org/apache/http/ssl/TrustStrategy
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:555)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:87)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
	... 135 more

This occurs on Version 0.1.8, Version 0.1.6 seems fine

**Comment by ahmedyha** [comment]
It looks a versioning problem, do you have the right dependency for HttpClient in the classpath?
