### ISSUE TITLE
Couchdb 2.3 changed the purge_seq field in the `DbInfo` response to be a string.  This now throws java.lang.NumberFormatException

### ISSUE THREAD

**Issue by simon-temple** [lightcouch/LightCouch#73]
Maybe need to add `purge_seq` getter on `DbInfo` class that returns seq as `String`

Here's the stack trace:

jvm 1    | com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: For input string: "0-g1AAAABXeJzLYWBgYMpgTmEQTM4vTc5ISXLIyU9OzMnILy7JAUnlsQBJhgYg9R8IshIZ8KhNZEiqhyjKAgBm5Rxs"
jvm 1    | 	at com.google.gson.internal.bind.TypeAdapters$11.read(TypeAdapters.java:306)
jvm 1    | 	at com.google.gson.internal.bind.TypeAdapters$11.read(TypeAdapters.java:296)
jvm 1    | 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
jvm 1    | 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
jvm 1    | 	at com.google.gson.Gson.fromJson(Gson.java:927)
jvm 1    | 	at com.google.gson.Gson.fromJson(Gson.java:865)
jvm 1    | 	at org.lightcouch.CouchDbClientBase.get(CouchDbClientBase.java:553)
jvm 1    | 	at org.lightcouch.CouchDbContext.info(CouchDbContext.java:113)

**Comment by nasava** [comment]
Hi Simon, I discovered the same issue for myself with CouchDB 2.3.1 and lightcouch 0.2.0. Did you find a workaround or did you switch to another lib? 

The lightcouch project seems pretty inactive ...

**Comment by lightcouch** [comment]
Hi, 

fyi, a new release of lightcouch is rolling now for the compatibility with CouchDB 2.3

best regards

**Comment by chrisinmtown** [comment]
Will the new release be ready soon?  I don't see any commits newer than 2017, am I blind?

**Comment by jjrodrig** [comment]
We have solved this issue here IndabaConsultores@93b3f565fbc69d13df171305d2eec90600c05165 if you wish to use it while a new release of the library is released.

**Comment by lightcouch** [comment]
Apologies. The owner of the project was na. A new release ships today.
Regards

**Comment by jjrodrig** [comment]
Sorry, but I dont understand why you have deleted my comment. 
I think that it is helpful for any one to know that there is a solution for this issue in another fork while you publish a new release with the fix.  
Also, It could be helpfull for you as you can get the change from there if you whish.
